// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzgxdiaxqkcedfmjvyss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6Z3hkaWF4cWtjZWRmbWp2eXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczODY1ODcsImV4cCI6MjA1Mjk2MjU4N30.3dsdbFX5jLcRwCQSSEth1xUuZE_BWNiaEYXgK6KNGgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);